name: CI Akazaki

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Vérification du code source
    - name: Checkout code
      uses: actions/checkout@v3

    # Configuration de Java
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'

    # Installation des dépendances Maven
    - name: Install dependencies
      run: mvn install -DskipTests

    # Lancer les tests
    - name: Run tests
      run: mvn test

